fieldLayouts:
  6b8001e5-097a-46ed-a5e5-66a803a594c8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            heading: Hero
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 95016449-90ad-4380-be7a-64e487a1170d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f62f4afb-8cb0-4d62-a98f-84e62d7ead06
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aec83ffc-fa31-48be-a04d-94c3efe29c36
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f8f0889d-7e3d-40e5-b744-bac53baa0f30
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            heading: 'Top Marquee'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 5605177a-ede4-4783-8156-183fba8f1007
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Column Callout'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a52b0580-1dfe-4d5e-be7a-9f958fb4d8ed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: aef9fe86-6374-4236-9316-918a7449e6d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 086d30dc-b7c7-4b09-929e-288aacb5f57e
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
