contentColumnType: text
fieldGroup: d59c117a-32c7-4afd-b3ab-d74f6ee1ba1f
handle: homeCalloutHeadingRight
instructions: ''
name: 'Callout Heading Right'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
