enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  4ae0fdd2-3dff-4dca-b73e-347843888a6c:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
